pipeline { 
    agent any
    stages {
        stage('Compile Java') {
            steps {
                sh 'ls -l'  // List files to verify presence
                sh 'javac HelloWorld.java'
            }
        }
        stage('Run Java Program') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}
