pipeline { 
    agent any
    stages {
        stage('Check Workspace & Compile Java') {
            steps {
                script {
                    sh 'pwd'       // Print current directory (for debugging)
                    sh 'ls -l'     // List files (ensure HelloWorld.java is present)
                    sh 'javac HelloWorld.java'
                }
            }
        }
        stage('Run Java Program') {
            steps {
                script {
                    sh 'pwd'       // Debugging to check the current directory
                    sh 'ls -l'     // Confirm compiled HelloWorld.class exists
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
